### ISSUE TITLE
Missing or invalid "credential_handler" in Web app manifest.

### ISSUE THREAD

**Issue by oznfc** [credential-handler/authn.io#112]
I'm trying connect from mylocal to authn  working local. ı have a this error. any idea ? 

```Missing or invalid "credential_handler" in Web app manifest. ```

**Comment by dlongley** [comment]
You need to include a `credential_handler` section in your `manifest.json` file for your credential handler that defines the URL the mediator (authn.io) will load if the user selects your credential handler (digital wallet):

**Comment by dlongley** [comment]
Closing since this has been answered -- feel free to re-open if there's still a problem here. Thanks!
