### ISSUE TITLE
The "Store Credentials" screen should not say "send credentials"

### ISSUE THREAD

**Issue by BigBlueHat** [credential-handler/authn.io#143]
It'd be best to stick with the "store" language--i.e. replace `send` with `store` on this line:
https://github.com/credential-handler/authn.io/blob/3beb697d428fb8a99ccd882f9d6405d23fe1a7da/web/components/MediatorGreeting.vue#L58

Here's a screenshot:
![image](https://github.com/credential-handler/authn.io/assets/43209/0aba5ea0-022d-4453-a07d-bee34a9ec8be)

The store language would be more consistent and feel more stable--vs. "send".

**Comment by dlongley** [comment]
Literally replacing that word (which might not be what you meant) would result in text that's a bit awkward:

`The following website wants to store credentials to you`

So a couple other options:

A: `The following website wants you to store credentials`
B: `The following website has credentials for you to store`

Would you prefer either of these -- or could you make another suggestion?

**Comment by BigBlueHat** [comment]
Good call. I'd expected the last "to" to also be replaced (and I should have explained that)...so `The following website wants to store credentials for you`--but I clearly misunderstood what step in the process things were at (which is part of why I'm reading all the text these days). 😉 

So, of the options mentioned B. `The following website has credentials for you to store` is my favorite.

I'll send a PR with that. If you prefer something else, I can change it.
