### ISSUE TITLE
Allow localhost registration

### ISSUE THREAD

**Issue by clehner** [credential-handler/authn.io#154]
HTTP (plaintext) could be allowed on localhost domains and IP addresses (127.X, ::1, `*.localhost`), considering the local origin(s) as secure ("Potentially Trustworthy" https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy) for wallet app registration/installation.
This would enable local (private) web app instances without requiring CA/SSL certificates (or even a web server in the case of `file:` URLs); this would also assist development.
Currently the installation attempt from `http://localhost` results in "Permission denied" ("DOMException: The operation is insecure." in console log) Screenshot: https://lehnerstudios.com/2023/10/19/localhost-chapi-authnio-error.png

**Comment by dlongley** [comment]
We should figure out if we can make this happen. It could be that it's the browser and none of our code specifically throwing that `DOMException` -- in which case it's not something we control.

**Comment by clehner** [comment]
Update: installation (registration), issuance (store) and presentation (get) were successful with my wallet at http://localhost, http://127.0.0.1, http://foo.localhost, and http://127.0.0.4:7001. I'm not sure what changed but I think I have a little more understanding now.

https://lehnerstudios.com/2023/10/25/chapi-local-wallet.png

The `DOMException` is thrown by call to `caches.open` (https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/open) and caught (logged) without breaking: https://github.com/credential-handler/authn.io/blob/d670692cc851ab1ed385738b789b01d6fe3b83c5/web/mediator/manifest.js#L28
Skipping cache for manifest fetch from localhost should be OK since avoiding network trips to the local web app is less likely to be a concern (notwithstanding it could be a local proxy/tunnel to a remote server). I did not find a difference in cache invalidation: making changes to the wallet's manifest, the localhost-registered one updated in the picker just as the HTTPS-registered one.

The operation that fails is registration from as wallet on a private IP address. I guess it is not to be expected that the browser would detect the IP address is for the local interface or a "trusted network". Interestingly, the favicon fetch succeeds (in network log) but not the fetch of the manifest ("Mixed Block" – "TypeError: NetworkError when attempting to fetch resource.") and this doesn't look like CORS (no OPTIONS request). Anyway this issue was concerned with localhost use specifically so I would close it now.
https://lehnerstudios.com/2023/10/25/manifest-blocked-1.png
https://lehnerstudios.com/2023/10/25/manifest-blocked-2.png
