### ISSUE TITLE
Allow use as free software

### ISSUE THREAD

**Issue by clehner** [credential-handler/authn.io#155]
It should be possible (ideal - requesting) to use CHAPI/polyfill with a fully free/libre (open source) stack - not depending on nonfree/proprietary software. This project authn.io (CHAPI mediator) is freely-licensed but depends on bedrock libraries for the build process (dev-dependencies) which are not.

**Comment by dlongley** [comment]
Every `bedrock` dependency used here is now available using the Apache-2.0 license. We should update the package.json to use the latest, but we should be able to close this issue now.

**Comment by dlongley** [comment]
Closing as completed, latest dev install should use Apache-2.0 license.

**Comment by clehner** [comment]
Thanks! :pray:
